### ISSUE TITLE
SyntaxError: Unexpected token function 

### ISSUE THREAD

**Issue by minokoko** [zezhipeng/mina-loader#1]
这个情况是我的电脑少装了什么东西吗？每次都会报这个错误，不知道咋解决

ERROR in ./app/index.mina
Module build failed: C:\Users\jessyon\Desktop\webpack\node_modules\wechat-mina-loader\lib\render-wxml.js:15
module.exports = async function (template) {
                                  
                        ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\jessyon\Desktop\webpack\node_modules\wechat-mina-loader\index.js:2:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at loadLoader (C:\Users\jessyon\AppData\Roaming\npm\node_modules\webpack\node_modules\_loader-runner@2.3.0@loader-ru
nner\lib\loadLoader.js:13:17)
    at iteratePitchingLoaders (C:\Users\jessyon\AppData\Roaming\npm\node_modules\webpack\node_modules\_loader-runner@2.3
.0@loader-runner\lib\LoaderRunner.js:169:2)
    at runLoaders (C:\Users\jessyon\AppData\Roaming\npm\node_modules\webpack\node_modules\_loader-runner@2.3.0@loader-ru
nner\lib\LoaderRunner.js:362:2)
    at NormalModule.doBuild (C:\Users\jessyon\AppData\Roaming\npm\node_modules\webpack\lib\NormalModule.js:182:3)
    at NormalModule.build (C:\Users\jessyon\AppData\Roaming\npm\node_modules\webpack\lib\NormalModule.js:275:15)
    at Compilation.buildModule (C:\Users\jessyon\AppData\Roaming\npm\node_modules\webpack\lib\Compilation.js:149:10)
    at factoryCallback (C:\Users\jessyon\AppData\Roaming\npm\node_modules\webpack\lib\Compilation.js:342:12)
    at factory (C:\Users\jessyon\AppData\Roaming\npm\node_modules\webpack\lib\NormalModuleFactory.js:241:5)
    at applyPluginsAsyncWaterfall (C:\Users\jessyon\AppData\Roaming\npm\node_modules\webpack\lib\NormalModuleFactory.js:
94:13)
    at C:\Users\jessyon\AppData\Roaming\npm\node_modules\webpack\node_modules\_tapable@0.2.8@tapable\lib\Tapable.js:268:
11
    at NormalModuleFactory.params.normalModuleFactory.plugin (C:\Users\jessyon\AppData\Roaming\npm\node_modules\webpack\
lib\CompatibilityPlugin.js:52:5)
    at NormalModuleFactory.applyPluginsAsyncWaterfall (C:\Users\jessyon\AppData\Roaming\npm\node_modules\webpack\node_mo
dules\_tapable@0.2.8@tapable\lib\Tapable.js:272:13)
    at resolver (C:\Users\jessyon\AppData\Roaming\npm\node_modules\webpack\lib\NormalModuleFactory.js:69:10)
 @ ./app/main.js 2:0-23

**Comment by luoquanquan** [comment]
请问兄台是怎么解决, 我也遇到了这个问题
